#!/bin/bash
# @raycast.schemaVersion 1
# @raycast.title Pensumhefte Databaser Focus
# @raycast.mode silent
# @raycast.icon 📖
# @raycast.author Anders Bekkevard
# Generated by generate-history-scripts.sh; edit focus-configs.json.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/browser.sh"
browser_control focus pensumhefte-databaser
