#!/usr/bin/env python3
"""Generate Raycast metadata wrappers; browser behavior is resolved at runtime."""
import json
from pathlib import Path
import shlex

root = Path(__file__).resolve().parents[1]
entries = json.loads((root / 'focus-configs.json').read_text())
for entry in entries:
    name = entry['name']
    if '/' in name or '\n' in name or name in {'.', '..'}:
        raise ValueError(f'Invalid command name: {name!r}')
    title, icon = entry['title'], entry['icon']
    if '\n' in title + icon:
        raise ValueError('Metadata must be a single line')
    path = root / 'focus' / f'{name}-focus.sh'
    path.write_text(f'''#!/bin/bash
# @raycast.schemaVersion 1
# @raycast.title {title}
# @raycast.mode silent
# @raycast.icon {icon}
# @raycast.author Anders Bekkevard
# Generated by generate-history-scripts.sh; edit focus-configs.json.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
source "$SCRIPT_DIR/../lib/browser.sh"
browser_control focus {shlex.quote(name)}
''')
    path.chmod(0o755)
print(f'Generated {len(entries)} focus commands')
